environment:
    matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          WLP_VERSION: 19.0.0_09
          WLP_LICENSE: L-CTUR-BEN4AJ
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          WLP_VERSION: 19.0.0_06
          WLP_LICENSE: L-CTUR-BCTPHF

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\ci-ant
build_script:
    - "mvn verify -Ponline-its -Dinvoker.streamLogs=true -DwlpVersion=%WLP_VERSION% -DwlpLicense=%WLP_LICENSE% -e"

test: off
